[versions]
agp = "9.2.1"

[libraries]
libxposed-api = { group = "io.github.libxposed", name = "api", version = "101.0.1" }
libxposed-service = { group = "io.github.libxposed", name = "service", version = "101.0.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }